apiVersion: v1
kind: Plugin
metadata:
  author: LangBot Developer
  name: waifu_bot
  repository: ''
  version: 2.0.0
  description:
    en_US: A chatbot with real emotions, memory and personality system
    zh_Hans: 一个拥有真实情感、记忆和人格系统的聊天机器人
  label:
    en_US: WaifuBot
    zh_Hans: Waifu情感机器人
  icon: assets/icon.svg
spec:
  config:
    # 通用设置
    - name: character
      type: string
      default: "default"
      label:
        en_US: Character Card
        zh_Hans: 角色卡
      description:
        en_US: Character card name, use "default" for default template, "off" to disable preset
        zh_Hans: 角色卡名称，使用"default"时会使用默认模板，"off"时不使用角色预设
    - name: summarization_mode
      type: boolean
      default: true
      label:
        en_US: Long-term Memory
        zh_Hans: 长期记忆
      description:
        en_US: Whether to enable long-term memory summarization
        zh_Hans: 是否开启长期记忆
    - name: story_mode
      type: boolean
      default: false
      label:
        en_US: Story Mode
        zh_Hans: 剧情模式
      description:
        en_US: Enable story mode (narration, status bar), private chat only
        zh_Hans: 是否开启剧情模式（旁白、状态栏），仅私聊模式生效
    - name: thinking_mode
      type: boolean
      default: false
      label:
        en_US: Thinking Mode
        zh_Hans: 思维链模式
      description:
        en_US: Whether to enable thinking chain mode
        zh_Hans: 是否开启思维链模式
    - name: personate_mode
      type: boolean
      default: true
      label:
        en_US: Personification Mode
        zh_Hans: 拟人化模式
      description:
        en_US: Enable personification (typing time, segmented reply)
        zh_Hans: 是否启用拟人化（打字时间、分段回复）
    - name: jail_break_mode
      type: string
      default: "off"
      label:
        en_US: Jail Break Mode
        zh_Hans: 破限模式
      description:
        en_US: "Jail break mode, options: off/before/after/end/all"
        zh_Hans: "破限模式，可选值：off/before/after/end/all"
    - name: langbot_group_rule
      type: boolean
      default: false
      label:
        en_US: LangBot Group Rule
        zh_Hans: LangBot群规则
      description:
        en_US: Whether to inherit LangBot's group message response rules
        zh_Hans: 是否继承LangBot的群消息响应规则
    - name: ignore_prefix
      type: array[string]
      default: ["/"]
      label:
        en_US: Ignore Prefix
        zh_Hans: 忽略前缀
      description:
        en_US: List of message prefixes to ignore
        zh_Hans: 忽略的消息前缀列表
    
    # 思考模块
    - name: conversation_analysis
      type: boolean
      default: true
      label:
        en_US: Conversation Analysis
        zh_Hans: 对话分析
      description:
        en_US: Whether to enable scene analysis
        zh_Hans: 是否启用场景分析
    - name: display_thinking
      type: boolean
      default: false
      label:
        en_US: Display Thinking
        zh_Hans: 显示思考
      description:
        en_US: Whether to show inner thoughts
        zh_Hans: 是否显示内心活动
    - name: analyze_max_conversations
      type: integer
      default: 9
      label:
        en_US: Max Analysis Conversations
        zh_Hans: 最大分析对话数
      description:
        en_US: Maximum number of conversations used for analysis
        zh_Hans: 用于生成分析的最大对话数量
    - name: max_thinking_words
      type: integer
      default: 30
      label:
        en_US: Max Thinking Words
        zh_Hans: 最大思考字数
      description:
        en_US: Maximum number of words for thinking
        zh_Hans: 最大思考字数
    
    # 记忆模块
    - name: short_term_memory_size
      type: integer
      default: 2000
      label:
        en_US: Short-term Memory Size
        zh_Hans: 短期记忆大小
      description:
        en_US: Maximum length of short-term memory (characters)
        zh_Hans: 短期记忆的最大长度（字）
    - name: retrieve_top_n
      type: integer
      default: 3
      label:
        en_US: Retrieve Top N
        zh_Hans: 检索数量
      description:
        en_US: Number of relevant long-term memories to retrieve each time
        zh_Hans: 每次提取的相关长期记忆数量
    - name: recall_once
      type: integer
      default: 3
      label:
        en_US: Recall Once
        zh_Hans: 单次回忆数量
      description:
        en_US: Number of long-term memories recalled to memory pool each time
        zh_Hans: 每次召回到记忆池中的长期记忆数量
    - name: session_memories_size
      type: integer
      default: 6
      label:
        en_US: Session Memory Size
        zh_Hans: 会话记忆池容量
      description:
        en_US: Capacity of session memory pool
        zh_Hans: 记忆池容量
    - name: summary_max_tags
      type: integer
      default: 30
      label:
        en_US: Max Summary Tags
        zh_Hans: 最大摘要标签数
      description:
        en_US: Maximum number of tags per long-term memory
        zh_Hans: 每段长期记忆的最大标签数量
    
    # 群聊设置
    - name: response_min_conversations
      type: integer
      default: 1
      label:
        en_US: Min Response Conversations
        zh_Hans: 最小回复对话数
      description:
        en_US: Minimum number of conversations to trigger group reply
        zh_Hans: 群聊触发回复的最小对话数量
    - name: response_rate
      type: number
      default: 1.0
      label:
        en_US: Response Rate
        zh_Hans: 回复概率
      description:
        en_US: Probability of replying after reaching minimum conversations (0-1)
        zh_Hans: 群聊触达到最小对话数量后回复的机率（0-1）
    - name: group_response_delay
      type: integer
      default: 0
      label:
        en_US: Group Response Delay
        zh_Hans: 群聊回复延迟
      description:
        en_US: Group message merge waiting time (seconds)
        zh_Hans: 群聊消息合并等待时间（秒）
    - name: blacklist
      type: array[string]
      default: []
      label:
        en_US: Blacklist
        zh_Hans: 黑名单
      description:
        en_US: Group blacklist, automatically filter messages from listed users
        zh_Hans: 群聊黑名单，自动过滤来自列表中用户的消息
    - name: repeat_trigger
      type: integer
      default: 2
      label:
        en_US: Repeat Trigger
        zh_Hans: 复读触发
      description:
        en_US: Minimum repeat times to trigger group repeat (0 to disable)
        zh_Hans: 群聊触发复读的最小重复次数（0为关闭）
    
    # 拟人化设置
    - name: bracket_rate
      type: array[number]
      default: [0.1, 0.1]
      label:
        en_US: Bracket Rate
        zh_Hans: 括号语概率
      description:
        en_US: Probability of adding brackets at the end of reply
        zh_Hans: 回复末尾加括号的机率
    - name: personate_delay
      type: integer
      default: 0
      label:
        en_US: Personate Delay
        zh_Hans: 分段回复间隔
      description:
        en_US: Interval for segmented replies (seconds), 0 for default (2 characters per second)
        zh_Hans: 分段回复的间隔（秒），0为默认间隔（两个字一秒）
    
    # 私聊剧情模式
    - name: display_value
      type: boolean
      default: false
      label:
        en_US: Display Affection Value
        zh_Hans: 显示好感度
      description:
        en_US: Whether to display affection value after each reply
        zh_Hans: 是否每次回复后显示好感度数值
    - name: max_narrat_words
      type: integer
      default: 30
      label:
        en_US: Max Narration Words
        zh_Hans: 最大旁白字数
      description:
        en_US: Maximum number of words for narration
        zh_Hans: 最大旁白字数
    - name: narrat_max_conversations
      type: integer
      default: 8
      label:
        en_US: Max Narration Conversations
        zh_Hans: 最大旁白对话数
      description:
        en_US: Maximum number of conversations used for narration
        zh_Hans: 用于生成旁白的最大对话数量
    - name: value_game_max_conversations
      type: integer
      default: 5
      label:
        en_US: Max Affection Analysis Conversations
        zh_Hans: 最大好感度分析对话数
      description:
        en_US: Maximum conversations used to determine affection change
        zh_Hans: 判定好感度变化时使用的最大对话数量
    - name: intervals
      type: array[integer]
      default: []
      label:
        en_US: Auto Narration Intervals
        zh_Hans: 自动旁白间隔
      description:
        en_US: Intervals to automatically trigger narration (seconds)
        zh_Hans: 自动触发旁白推进剧情的时间间隔（秒）
    - name: person_response_delay
      type: integer
      default: 5
      label:
        en_US: Private Response Delay
        zh_Hans: 私聊回复延迟
      description:
        en_US: Private message merge waiting time (seconds)
        zh_Hans: 私聊消息合并等待时间（秒）
    - name: continued_rate
      type: number
      default: 0.0
      label:
        en_US: Continued Speech Rate
        zh_Hans: 延续发言概率
      description:
        en_US: Probability of continuing speech after automatic reply (0-1)
        zh_Hans: 自动触发回复后继续发言的机率（0-1）
    - name: continued_max_count
      type: integer
      default: 2
      label:
        en_US: Max Continued Speech Count
        zh_Hans: 最大延续发言次数
      description:
        en_US: Maximum number of continued speeches in private chat
        zh_Hans: 私聊最大延续发言次数
    
    # 主动发言模式
    - name: proactive_target_user_id
      type: string
      default: "off"
      label:
        en_US: Proactive Target User ID
        zh_Hans: 主动发言目标用户
      description:
        en_US: Target user ID for proactive messages, "off" to disable
        zh_Hans: 主动发送消息的目标用户ID，"off"为关闭
    - name: proactive_greeting_enabled
      type: boolean
      default: false
      label:
        en_US: Proactive Greeting
        zh_Hans: 主动发言
      description:
        en_US: Whether to enable proactive greeting mode
        zh_Hans: 是否开启主动发言模式
    - name: proactive_greeting_probability
      type: integer
      default: 50
      label:
        en_US: Proactive Probability
        zh_Hans: 主动发言概率
      description:
        en_US: Probability of triggering proactive greeting (0-100)
        zh_Hans: 触发主动发言的几率（0-100）
    - name: proactive_min_inactive_hours
      type: integer
      default: 3
      label:
        en_US: Min Inactive Hours
        zh_Hans: 最小不活跃小时数
      description:
        en_US: Minimum hours of user inactivity
        zh_Hans: 用户不活跃的最小小时数
    - name: proactive_do_not_disturb_start
      type: string
      default: "23:00"
      label:
        en_US: Do Not Disturb Start
        zh_Hans: 勿扰开始时间
      description:
        en_US: "Do not disturb start time (format: 'xx:xx')"
        zh_Hans: "勿扰时间开始（格式：'xx:xx'）"
    - name: proactive_do_not_disturb_end
      type: string
      default: "08:00"
      label:
        en_US: Do Not Disturb End
        zh_Hans: 勿扰结束时间
      description:
        en_US: "Do not disturb end time (format: 'xx:xx')"
        zh_Hans: "勿扰时间结束（格式：'xx:xx'）"
    - name: loop_time
      type: integer
      default: 1800
      label:
        en_US: Loop Time
        zh_Hans: 循环检查时间
      description:
        en_US: Proactive greeting loop check time (seconds)
        zh_Hans: 主动发言循环检查时间（秒）
    
    # 管理员设置
    - name: admin_ids
      type: array[string]
      default: []
      label:
        en_US: Admin IDs
        zh_Hans: 管理员ID
      description:
        en_US: List of admin user IDs
        zh_Hans: 管理员用户ID列表
  
  components:
    - type: event_listener
      name: on_message
      file: components/event_listener/on_message.py
    - type: command
      name: affection
      file: components/commands/affection.py
    - type: command
      name: memory
      file: components/commands/memory.py
execution:
  python:
    path: main.py
    attr: WaifuBotPlugin