apiVersion: v1
kind: Plugin
metadata:
  author: LangBot Developer
  name: waifu_bot
  repository: ''
  version: 2.0.0
  description:
    en_US: A chatbot with real emotions, memory and personality system
    zh_Hans: 一个拥有真实情感、记忆和人格系统的聊天机器人
  label:
    en_US: WaifuBot
    zh_Hans: Waifu情感机器人
  icon: assets/icon.svg
spec:
  config:
    # API配置
    - name: api_key
      type: string
      default: ""
      label:
        en_US: API Key
        zh_Hans: API密钥
      description:
        en_US: API key for LLM model
        zh_Hans: LLM模型的API密钥
    # 角色卡配置
    # 通用设置
    - name: character
      type: string
      default: "cute_neko"
      label:
        en_US: Character Card (Private)
        zh_Hans: 角色卡（私信）
      description:
        en_US: Character card name for private messages, use "default" for default template, "off" to disable preset
        zh_Hans: 私信使用的角色卡名称，使用"default"时会使用默认模板，"off"时不使用角色预设
    - name: group_character
      type: string
      default: "cute_neko"
      label:
        en_US: Character Card (Group)
        zh_Hans: 角色卡（群聊）
      description:
        en_US: Character card name for group messages, use "default" for default template, "off" to disable preset
        zh_Hans: 群聊使用的角色卡名称，使用"default"时会使用默认模板，"off"时不使用角色预设
    - name: user_character_mappings
      type: object
      default: {}
      label:
        en_US: User Character Mappings
        zh_Hans: 用户角色映射
      description:
        en_US: Map user IDs to specific character cards. Use JSON object format with {}.
        zh_Hans: 将用户ID映射到特定的角色卡，使用JSON对象格式，注意用大括号{}。
    - name: ignore_prefix
      type: array
      default: ["/"]
      label:
        en_US: Ignore Prefix
        zh_Hans: 忽略前缀
      description:
        en_US: List of message prefixes to ignore
        zh_Hans: 忽略的消息前缀列表
    
    # 思考模块
    - name: analyze_max_conversations
      type: integer
      default: 9
      label:
        en_US: Max Analysis Conversations
        zh_Hans: 最大分析对话数
      description:
        en_US: Maximum number of conversations used for analysis
        zh_Hans: 用于生成分析的最大对话数量
    - name: max_thinking_words
      type: integer
      default: 30
      label:
        en_US: Max Thinking Words
        zh_Hans: 最大思考字数
      description:
        en_US: Maximum number of words for thinking
        zh_Hans: 最大思考字数
    
    # 记忆模块
    - name: short_term_memory_size
      type: integer
      default: 2000
      label:
        en_US: Short-term Memory Size
        zh_Hans: 短期记忆大小
      description:
        en_US: Maximum length of short-term memory (characters)
        zh_Hans: 短期记忆的最大长度（字）
    - name: retrieve_top_n
      type: integer
      default: 3
      label:
        en_US: Retrieve Top N
        zh_Hans: 检索数量
      description:
        en_US: Number of relevant long-term memories to retrieve each time
        zh_Hans: 每次提取的相关长期记忆数量
    - name: recall_once
      type: integer
      default: 3
      label:
        en_US: Recall Once
        zh_Hans: 单次回忆数量
      description:
        en_US: Number of long-term memories recalled to memory pool each time
        zh_Hans: 每次召回到记忆池中的长期记忆数量
    - name: session_memories_size
      type: integer
      default: 6
      label:
        en_US: Session Memory Size
        zh_Hans: 会话记忆池容量
      description:
        en_US: Capacity of session memory pool
        zh_Hans: 记忆池容量
    - name: summary_max_tags
      type: integer
      default: 30
      label:
        en_US: Max Summary Tags
        zh_Hans: 最大摘要标签数
      description:
        en_US: Maximum number of tags per long-term memory
        zh_Hans: 每段长期记忆的最大标签数量
    
    # 群聊设置
    - name: repeat_trigger
      type: integer
      default: 2
      label:
        en_US: Repeat Trigger
        zh_Hans: 复读触发
      description:
        en_US: Minimum repeat times to trigger group repeat (0 to disable)
        zh_Hans: 群聊触发复读的最小重复次数（0为关闭）
    
    # 拟人化设置
    - name: bracket_rate
      type: array
      default: [0.1, 0.1]
      label:
        en_US: Bracket Rate
        zh_Hans: 括号语概率
      description:
        en_US: Probability of adding brackets at the end of reply
        zh_Hans: 回复末尾加括号的机率
    
    # 好感度设置
    - name: display_value
      type: boolean
      default: false
      label:
        en_US: Display Affection Value
        zh_Hans: 显示好感度
      description:
        en_US: Whether to display affection value after each reply
        zh_Hans: 是否每次回复后显示好感度数值
    
    # 主动发言模式
    - name: proactive_target_user_id
      type: string
      default: "off"
      label:
        en_US: Proactive Target User ID
        zh_Hans: 主动发言目标用户
      description:
        en_US: Target user ID for proactive messages, "off" to disable
        zh_Hans: 主动发送消息的目标用户ID，"off"为关闭
    - name: proactive_greeting_enabled
      type: boolean
      default: false
      label:
        en_US: Proactive Greeting
        zh_Hans: 主动发言
      description:
        en_US: Whether to enable proactive greeting mode
        zh_Hans: 是否开启主动发言模式
    - name: proactive_greeting_probability
      type: integer
      default: 50
      label:
        en_US: Proactive Probability
        zh_Hans: 主动发言概率
      description:
        en_US: Probability of triggering proactive greeting (0-100)
        zh_Hans: 触发主动发言的几率（0-100）
    - name: proactive_min_inactive_minutes
      type: integer
      default: 180
      label:
        en_US: Inactive Minutes
        zh_Hans: 不活跃分钟数
      description:
        en_US: Minimum minutes of user inactivity before sending proactive message
        zh_Hans: 用户不活跃达到此时间后发送主动消息
    - name: proactive_do_not_disturb_start
      type: string
      default: "23:00"
      label:
        en_US: Do Not Disturb Start
        zh_Hans: 勿扰开始时间
      description:
        en_US: "Do not disturb start time (format: 'xx:xx')"
        zh_Hans: "勿扰时间开始（格式：'xx:xx'）"
    - name: proactive_do_not_disturb_end
      type: string
      default: "08:00"
      label:
        en_US: Do Not Disturb End
        zh_Hans: 勿扰结束时间
      description:
        en_US: "Do not disturb end time (format: 'xx:xx')"
        zh_Hans: "勿扰时间结束（格式：'xx:xx'）"
    - name: loop_time
      type: integer
      default: 60
      label:
        en_US: Loop Time
        zh_Hans: 循环检查时间
      description:
        en_US: Proactive greeting loop check time (seconds)
        zh_Hans: 主动发言循环检查时间（秒）
    
    # 管理员设置
    - name: admin_ids
      type: array
      default: []
      label:
        en_US: Admin IDs
        zh_Hans: 管理员ID
      description:
        en_US: List of admin user IDs
        zh_Hans: 管理员用户ID列表
  
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
    Command:
      fromDirs:
      - path: components/commands/
  resources:
    - path: config/
    - path: templates/
execution:
  python:
    path: main.py
    attr: WaifuBotPlugin
